version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    image: siokim002/storyboat_frontend  # Docker Hub에 푸시할 프론트엔드 이미지 이름


  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    image: siokim002/storyboat_backend  # Docker Hub에 푸시할 프론트엔드 이미지 이름
